version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/GreateBelt.Pn/GreateBelt.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/GreateBelt.Pn/GreateBelt.Pn.Test"
  schedule:
    interval: daily