<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>../../../eFormAPI.Web/Plugins/GreateBelt.Pn</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>../../../eFormAPI.Web/Plugins/GreateBelt.Pn</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="SentryDsn" Value="https://2cd3071eb1d210f5384914322eb6e765@o4506241219428352.ingest.us.sentry.io/4508266870145024" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\localization.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.NETCore.Plugins" Version="2.0.0" />
    <PackageReference Include="Microting.eForm" Version="10.0.41" />
    <PackageReference Include="Microting.eFormApi.BasePn" Version="10.0.36" />
    <PackageReference Include="Microting.ItemsPlanningBase" Version="10.0.40" />
    <PackageReference Include="Sentry" Version="6.11.1" />
  </ItemGroup>

</Project>
